# This file was generated by the deal.II library.


#
# For a description of the GNUPLOT format see the GNUPLOT manual.
#
# <x> <y> <id> <function> 
0.384504 0.024157 0 1 

0.0501836 0.438366 1 3.18846e-10 

0.236008 0.313141 2 4.83695e-05 

0.047196 0.543521 3 8.65974e-15 

0.0744251 0.568103 4 7.21645e-16 

0.393171 0.950348 5 0 

0.505169 0.713598 6 0 

0.662859 0.680424 7 0 

0.658979 0.703224 8 0 

0.824102 0.729598 9 0 

