# This file was generated by the deal.II library.


#
# For a description of the GNUPLOT format see the GNUPLOT manual.
#
# <x> <y> <id> <initial anomaly> 
0.37505 0.0241928 0 1 

0.0519723 0.457357 1 3.18846e-10 

0.235207 0.326321 2 4.83695e-05 

0.0493531 0.558387 3 8.65974e-15 

0.0778549 0.581548 4 7.21645e-16 

0.396663 0.950397 5 0 

0.516472 0.71185 6 0 

0.671404 0.674603 7 0 

0.667517 0.6981 8 0 

0.827325 0.723469 9 0 

